#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gdscript2 = env_modules.Clone()

# Core sources for gdscript2.
env_gdscript2.add_source_files(env.modules_sources, "*.cpp")

# Tests will be added incrementally; keep the toggle in place.
if env["tests"]:
    env_gdscript2.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_gdscript2.add_source_files(env.modules_sources, "./tests/*.cpp")
